---
title: "Lab 03 - Nobel laureates"
author: "Alex Connolly"
date: "2-Feb-2022"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1

```{r summary}
summary(nobel)
```

935 observations, each row is a laureate, 26 variables

### Exercise 2

```{r filter}
nobel_living <- nobel
nobel_living %>% 
  filter(country != "NA") %>%
  filter(gender != "org") %>%
  filter(is.na(died_date))

```
```{r US}
nobel_living <- nobel_living %>%
  mutate(country_us = if_else(country == "USA", "USA", "Other"))
```
```{r Topics}
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
```

### Exercise 3




### Exercise 4

```{r born-country}
nobel_living <- nobel_living %>%
  mutate(born_country_us = if_else(born_country == "USA", "USA", "Other"))
```


### Exercise 5

```{r}

```


### Exercise 6

...
